description: |
  The buttons use a simple design in order to unite with the website's minimalist theme.

  Buttons can be combined with font-size classes to make different sized buttons.
patterns:
  navigation:
    title: "Navigation"
    description: |
      The <i>Navigation</i> button is to used in the navigation along the website.
    background: "--color-primary-light"
  footer:
    title: "Footer"
    description: |
      The <i>Footer</i> button is to be used in the footer and can be combined with different text weights.
  solid-dark-blue:
    title: "Solid Dark Blue"
    description: |
      The <i>Solid Dark Blue</i> button is to be used on the home and checkout page.
    background: "--color-primary-light"
  transparent-dark-blue:
    title: "Transparent Dark Blue"
    description: |
      The <i>Transparent Dark Blue</i> button can be on the homepage along with the banners.
  light:
    title: "Light"
    description: |
      The <i>Light</i> button can be used in the product detail page for accenting the related crystals colour and can be combined with different colours to match the crystal.
    background: "--color-primary-light"
  ghost:
    title: "Ghost"
    description: |
      The <i>Ghost</i> button is to be used for smaller detail buttons, included on most pages. It can be minimized with a different font-size.
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      The <i>Breadcrumbs</i> button is to be combined into the breadcrumb navigation.
    background: "--color-primary-light"
  gray-and-blue-hover:
    title: "Gray and Blue Hover"
    description: |
      The <i>Gray and Blue Hover</i> is to be used in the checkout page and products list page and can be minimized with a different font-size.
  gray-and-red-hover:
    title: "Gray and Red Hover"
    description: |
      The <i>Gray and Red Hover</i> is to be used in the product details page and can be minimized with a different font-size.
    background: "--color-primary-light"
  cart:
    title: "Cart"
    description: |
      The <i>Cart</i> button is to stay at the top-right corner throughout every page of the website. It can be minimized with a different font-size.
