description: |
  The buttons use a simple design in order to unite with the website's minimalist theme.

  Buttons can be combined with font-size classes to make different sized buttons.
patterns:
  navigation:
    title: "Navigation"
    description: |
      The Navigation button is to used in the navigation.
    width: "12em"
    background: "--color-primary-light"
  footer:
    title: "Footer"
    description: |
      The Footer button is to be used in the footer and can be combined with different text weights.
    width: "12em"
  solid-dark-blue:
    title: "Solid Dark Blue"
    description: |
      The Solid Dark Blue button can be on the home and checkout page.
    width: "12em"
    background: "--color-primary-light"
  transparent-dark-blue:
    title: "Transparent Dark Blue"
    description: |
      The Transparent Dark Blue button can be on the home page on the banners.
    width: "12em"
  light:
    title: "Light"
    description: |
      The Light button can be used in the product details page for accenting the related crystals colour.
    width: "12em"
    background: "--color-primary-light"
  ghost:
    title: "Ghost"
    description: |
      The Ghost button is to be used for smaller detailed buttons, included on most pages. It can be minimized with a different font-size.
    width: "12em"
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      The Breadcrumbs button is to be used for the checkout page.
    width: "12em"
    background: "--color-primary-light"
  grey-and-blue-hover:
    title: "Grey and Blue Hover"
    description: |
      The Grey and Blue Hover is to be used in the checkout page and products list page and can be minimized with a different font-size.
    width: "12em"
  grey-and-red-hover:
    title: "Grey and Red Hover"
    description: |
      The Grey and Red Hover is to be used in the product details page and can be minimized with a different font-size.
    width: "12em"
    background: "--color-primary-light"
  cart:
    title: "Cart"
    description: |
      The Cart button is to stay at the top-right corner throughout every page of the website. It can be minimized with a different font-size.
    width: "12em"
