description: |
  The sections are formed to be used throughout the website wherever a section style is needed.

  Sections can be combined with cards, buttons, icons, grids and colours.
patterns:
  slideshow:
    title: "Slideshow Image Section"
    description: |
      The <i>Slideshow Image Section</i> is to be used on the homepage and other areas that require the showcasing of products. This can be combined with cards and icons.
  text-section:
    title: "Text Section"
    description: |
      The <i>Text Section</i> is to be used on the homepage and other areas in the website that require a stylised section with text.
  newsletter-section:
    title: "Newsletter Section"
    description: |
      The <i>Newsletter Section</i> is to be used on the homepage in order to promote users to interact with the business and recieve updates.
  crystal-info:
    title: "Crystal Information Section"
    description: |
      The <i>Crystal Info</i> is to be used on the product detail page in order to showcase the products information. This can be combined with different text and colours to relate to any crystal.
    width: "32em"
  products-showcasing:
    title: "Products Slideshow Section"
    description: |
      The <i>Products Showcasing</i> is to be used on the product details page in order to promote other similar products. This can be combined with cards and buttons.
