description: |
  The forms are formed to be used throughout the website wherever the input forms need be.

  Forms can be combined with buttons.
patterns:
  main-form:
    title: "Main Form Field"
    description: |
      The <i>Main Form</i> field is be used on the checkout pages and wherever the original form style is to be placed. It can be combined with headers and used in a grid system.
    width: "32em"
  radio-button-form:
    title: "Radio Button"
    description: |
      The <i>Radio Button Form</i> is to be used in place of any button style, and will be used in the checkout page.
    width: "32em"
  data-list:
    title: "Data List"
    description: |
      The <i>Data List</i> is to be used for any list form style needed throughout the website.
    width: "32em"
  date-picker:
    title: "Date Picker"
    description: |
      The <i>Date Picker</i> is to be used is there needs to be a date picker form style in the website.
    width: "32em"
  discount-code-input:
    title: "Discount Code"
    description: |
      The <i>Discount Code Input</i> is to be used on the checkout page and can be combined with buttons.
    width: "32em"
  email-input:
    title: "Email Input"
    description: |
      The <i>Email Input</i> can be used on the homepage in order for users to sign-up for email updates and can be combined with buttons.
    width: "32em"
  let-us-know-form:
    title: "Comment Form"
    description: |
      The <i>Let Us Know Form</i> is to be used for users to be able to directly contact the business. This can be combined with buttons.
    width: "32em"
