description: |
  The forms are formed to be used throughout the website wherever the input forms need be.

  Forms can be combined with buttons.
patterns:
  main-form:
    title: "Main Form Field"
    description: |
      The Main Form Field is be used on the checkout pages and wherever the original form style is to be placed. It can be combined with headers and used in a grid system.
    width: "12em"
  radio-button-form:
    title: "Radio Button"
    description: |
      The Radio Button is to be used in place of any button style, and will be used in the checkout page.
    width: "12em"
  data-list:
    title: "Data List"
    description: |
      The Data List is to be used for any list form style needed throughout the website.
    width: "12em"
  date-picker:
    title: "Date Picker"
    description: |
      The Date Picker is to be used is there needs to be a date picker form style in the website.
    width: "12em"
  discount-code-input:
    title: "Discount Code"
    description: |
      The Discount Code is to be used on the checkout page and can be combined with buttons.
    width: "12em"
  email-input:
    title: "Email Input"
    description: |
      The Email Input can be used on the homepage in order for users to sign-up for email updates and can be combined with buttons.
    width: "12em"
  let-us-know-form:
    title: "Comment Form"
    description: |
      The Comment Form is to be used for users to be able to directly contact the business. This can be combined with buttons.
    width: "12em"
