description: |
  The forms are formed to be used throughout the website wherever the input forms need be.

  Forms can be combined with buttons.
patterns:
  main-form:
    title: "Main Form Field"
    description: |
      The <i>Main Form</i> field is be used on the checkout page and wherever the original form style is to be placed. It can be combined with headers and used in a grid system.
    width: "32em"
    fields:
      - name: header
        type: string
        example: "EMAIL"
      - name: placeholder
        type: string
        example: "EMAIL"
      - name: error
        type: string
        example: "Please provide email"
      - name: for
        type: string
        example: "email"
      - name: id
        type: string
        example: "email"
      - name: aria
        type: string
        example: "email-error"
      - name: id-2
        type: string
        example: "email-error"
      - name: type
        type: string
        example: "email"
  radio-button-form:
    title: "Radio Button"
    description: |
      The <i>Radio Button Form</i> is to be used in place of any button style, and will be used in the checkout page.
    width: "32em"
    fields:
      - name: text
        type: string
        example: "Keep me up to date on news and exclusive offers"
  data-list:
    title: "Data List"
    description: |
      The <i>Data List</i> is to be used for any list form style needed throughout the website.
    width: "32em"
  date-picker:
    title: "Date Picker"
    description: |
      The <i>Date Picker</i> is to be used wherever the style is present on the website.
    width: "32em"
  discount-code-input:
    title: "Discount Code"
    description: |
      The <i>Discount Code Input</i> is to be used on the checkout page and can be combined with buttons.
    width: "32em"
    fields:
      - name: header
        type: string
        example: "GIFT CARD OR DISCOUNT CODE"
      - name: placeholder
        type: string
        example: "GIFT CARD OR DISCOUNT CODE"
  email-input:
    title: "Email Input"
    description: |
      The <i>Email Input</i> can be used on the homepage in order for users to sign-up for email updates and can be combined with buttons.
    width: "32em"
    fields:
      - name: header
        type: string
        example: "EMAIL"
      - name: placeholder
        type: string
        example: "name@example.com"
      - name: error
        type: string
        example: "Please provide email"
      - name: aria
        type: string
        example: "email-error"
      - name: id
        type: string
        example: "email-error"
  let-us-know-form:
    title: "Comment Form"
    description: |
      The <i>Let Us Know Form</i> is to be used for users to be able to directly contact the business. This can be combined with buttons.
    width: "32em"
    fields:
      - name: text
        type: string
        example: "Have a question, ask away!"
  search:
    title: "Search Form"
    description: |
      The <i>Search Form</i> is to be used in the header to allow users to find something throughout the entirety of the website.
    width: "32em"
  number-picker:
    title: "Number Picker"
    description: |
      The <i>Number Picker</i> is to be used in the areas that it is requires in order to allow users to pick a quantity or amount.
    width: "32em"
