description: |
  The cards follow a simple and minimalist theme to work together in a gridular form.

  Cards can be combined with buttons and images.
patterns:
  image-card:
    title: "Image Card"
    description: |
      The <i>Image Card</i> is to be used on the homepage for showcasing the products and any other section of the website that contains product showcasing.
    width: "24em"
    fields:
      - name: image
        type: string
        example: "amethyst.jpg"
  crystal-type-card:
    title: "Crystal Type Card"
    description: |
      The <i>Crystal Type Card</i> is to be used on the products list page to organize and show all the available products.
    width: "24em"
    fields:
      - name: data
        type: object
        data:
          source: "site.products[0]"
          type: Product
  crystal-info-card:
    title: "Crystal Info Card"
    description: |
      The <i>Crystal Info Card</i> is to be used on the products information page to allow user to directly purchase the product.
    width: "24em"
    fields:
      - name: image
        type: string
        example: "amethyst.jpg"
      - name: price
        type: string
        example: "$20.00"
      - name: button_text
        type: string
        example: "ADD TO CART"
        required: false
      - name: button_aria
        type: string
        example: "Add to cart button"
        required: false
      - name: button_col
        type: class
        classes:
          - btn-light
          - btn-orange
          - btn-yellow
          - btn-green
          - btn-blue
          - btn-purple
        required: false
  recommendations-card:
    title: "Recommendations Card"
    description: |
      The <i>Recommendations Card</i> is to be used on the products information page to show users other options similar to the ones they added to their cart.
    width: "24em"
    fields:
      - name: image
        type: string
        example: "amethyst.jpg"
      - name: header
        type: string
        example: "Amethyst"
      - name: price
        type: string
        example: "$20.00"
  check-out-card:
    title: "Checkout Card"
    description: |
      The <i>Checkout Card</i> is to be used for the checkout page in order to have a collected place with all the information for the prices and totals.
    width: "24em"
    fields:
      - name: price
        type: string
        example: "$20.00"
      - name: pricetotal
        type: string
        example: "$21.50"
      - name: text
        type: string
        example: "x1 Amethyst"
