description: |
  The banners are to be used to showcase the websites most important features.

  Banners can be combined with buttons, images, and the header.
patterns:
  call-to-action:
    title: "Call To Action"
    description: |
      The <i>Call To Action</i> banner is to be used on the homepage along with the image being a part of the header content.
  blog-banner:
    title: "Website Section"
    description: |
      The <i>Blog Banner</i> is to be used on the homepage and the style can be used in other areas of the website where there needs to be a call-out on a specific section of the website.
