description: |
  The banners are to be used to showcase the websites most important features.

  Banners can be combined with buttons, images, and the header.
patterns:
  call-to-action:
    title: "Call To Action Banner"
    description: |
      The Call-To-Action banner is to be used on the homepage along with the image being a part of header content.
    width: "12em"
  blog-banner:
    title: "Blog Banner"
    description: |
      The Blog banner is to be used on the homepage.
    width: "12em"
